### ISSUE TITLE
Consider moving jOOQ configuration stuff into a jooq element

### ISSUE THREAD

**Issue by lukaseder** [testcontainers/jooq-testcontainers-codegen-maven-plugin#12]
The plugin configuration looks like this:

```xml
<configuration>
        <!-- Plugin configuration -->
	<database>
	</database>

        <!-- delegation to flyway configuration -->
	<flyway>
	</flyway>

        <!-- delegation to liquibase configuration -->
	<liquibase>
	</liquibase>

        <!-- jooq configuration ? -->
	<generator>
		<database>
			<includes>.*</includes>
			<excludes>flyway_schema_history</excludes>
			<inputSchema>public</inputSchema>
		</database>
		<target>
			<packageName>org.jooq.codegen.maven.example</packageName>
			<directory>target/generated-sources/jooq</directory>
		</target>
	</generator>
</configuration>
```

I think it would be more clear to put jOOQ stuff inside a jOOQ element. I'm aware that this would produce an apparently unnecessary additional level of nesting, but:

- Even in jOOQ, `<generator/>` isn't a top level element. While `<jdbc/>` isn't necessary in most cases, it may be in some (e.g. to pass additional properties to the JDBC connection)
- There are elements like `<skip/>`, `<logging/>`, `<onError/>`, `<onUnused/>`, `<configurationFile/>`, and others that might be added in the future, which you won't support out of the box unless you nest jOOQ's configuration in a `<jooq/>` element. Note, you could add support for these in your own top level, but then that would be confusing as it wouldn't be clear if e.g. `<skip/>` belongs to jOOQ, or to you.
- Who knows if you're going to add more additional elements in the future, e.g. to clean up / post-process generated code, etc. Those elements will also possibly conflict with jOOQ stuff.

**Comment by sivaprasadreddy** [comment]
Hi @lukaseder 
Thanks for the suggestions. As you suggested, moving jOOQ related config inside `<jooq>...</jooq>`.

@romchellis would you like to work on these changes? If we can incorporate these changes by next week we can release 0.0.2 along with these changes.

**Comment by romchellis** [comment]
Hi @sivaprasadreddy , @lukaseder .
 I like suggested approach.
 Actually I'am already looking on possible solutions.Not sure that it will be completed by monday, possibly by the end of next week.
