### ISSUE TITLE
Please publish package to mvn central under org.testcontainers dependency

### ISSUE THREAD

**Issue by romchellis** [testcontainers/jooq-testcontainers-codegen-maven-plugin#2]
Hi, I'm interested in this plugin but i cannot try it as is inaccessible under org.testcontainers:jooq-testcontainers-codegen-maven-plugin.

Could you change target repository and publish it to maven central?
Thanks, Roman

**Comment by sivaprasadreddy** [comment]
Hi Roman,
This plugin is currently being migrated from my personal account to testcontainers organization.
You can use the following Maven coordinates for now until it is published from testcontainers org.

```
<plugin>
         <groupId>io.github.sivalabs</groupId>
         <artifactId>jooq-testcontainers-codegen-maven-plugin</artifactId>
         <version>0.0.2</version>
</plugin>
```

**Comment by romchellis** [comment]
Hello!
Thank you for response.
I have already done that in new microservice, but i hope you can understand that usage of plugin from an individual contributor in big companies usually is not allowed. Hope it will be available under testcontainers org soon.
Do you know any estimates when it might be published?

**Comment by sivaprasadreddy** [comment]
Published the plugin under testcontainers org. See https://central.sonatype.com/artifact/org.testcontainers/jooq-testcontainers-codegen-maven-plugin/0.0.1

**Comment by romchellis** [comment]
Great! Closing the issue
